name: zds_analysis
description: Lint rules for Dart and Flutter used internally at Zebra Technologies
homepage: https://github.com/ZebraDevs/zds_analysis
repository: https://github.com/ZebraDevs/zds_analysis
issue_tracker: https://github.com/zebradevs/zds_analysis/issues
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"
