name: zds_analysis
description: Lint rules for Dart and Flutter used internally at Zebra Technologies
homepage: https://github.com/ZebraDevs/zds_analysis
repository: https://github.com/ZebraDevs/zds_analysis
issue_tracker: https://github.com/ZebraDevs/zds_analysis
version: 1.1.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint_builder:
